tasks:
  - name: Run Background WasmCloud Host
    init: |
      sh wasm-cloud-base/init.sh
    command: |
      sh wasm-cloud-base/command.sh
      gp sync-done host-loaded
  - name: Fetch Example
    command: |
      gp await-port 4000 && ./wasm-cloud-base/fetch-repos.sh

ports:
  - port: 4000
    visibility: private
    onOpen: open-preview

github:
  prebuilds:
    master: true
    pullRequests: true
    addBadge: true
    branches: true

vscode:
  extensions:
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml

image:
  file: .gitpod.Dockerfile
